### ISSUE TITLE
how to use the event 'bfl:layerloaded'

### ISSUE THREAD

**Issue by luisfio1** [gabriel-russo/Leaflet.BetterFileLayer#1]
I want to add the new file, opened with BFL to L.control.layers, using:
// Better-FileLayer
	var fileLayer = L.Control.betterFileLayer(
			options = {
			style: () => myStyle,				
			},
).addTo(map);

		fileLayer.loader.on('bfl:layerloaded', function (event) { 
        	layerswitcher.addOverlay(event.layer, event.filename);
    	});
But it does not work. Which would be the correct function?

**Comment by gabriel-russo** [comment]
I don't fully understand your question, but i will try:

The event will trigger in the `map` container, so, you have to add a listener to you map instance like this:

```javascript
map.on("bfl:layerloaded", (ev) => {
         console.log("Your file was read successfully!! Event: ", ev);
});
```
Also, the plugin will add your layer into map automatically.

Try this:
```javascript
map.on('bfl:layerloaded', function (event) { 
             layerswitcher.addOverlay(event.layer, event.filename);
});
```
